Story1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('HOMEPAGE.urls')),
    path('', include('myspace.urls')),
    path('', include('story6.urls')),
]

story6/urls.py
from django.urls import path, include
from django.contrib import admin
from . import views
# from . import views
 
app_name = 'story6'
 
urlpatterns = [
    path('addActivity/', views.addActivity, name='addActivity'),
    path('listActivity/', views.listActivity, name='listActivity'),
    path('delete/<int:delete_id>/', views.deleteUser, name='delete'),
    path('deleteActivity/<int:delete_id>/', views.deleteActivity, name='deleteActivity'),
    path('join/<int:task_id>/', views.join, name='join'),
    # path('url-yang-diinginkan/', views.nama_fungsi, name='nama_fungsi')
    # path('profile/', views.profile, name='profile'),
    # dilanjutkan ...
]

story6/models.py
from django.db import models

 
# Create your models here.
class Activity(models.Model):
    activity_name = models.CharField(max_length = 100)
   
    def __str__(self):
        return self.activity_name
 
class Guest(models.Model):
    guest_name = models.CharField(max_length=64)
    activity = models.ForeignKey(Activity,
    on_delete=models.CASCADE, null=True, blank=True)
    def __str__(self):
        return self.guest_name

story6/forms.py
from django import forms 
 
class ActivityForm(forms.Form):
    activity_name = forms.CharField(
        label = "Activity name",
        widget = forms.TextInput(
            attrs = {
                'class':'form-control',
                'max_length : 100'
                'id' : 'fname',
                'placeholder' : 'Activity name',
            }
        )
    )
 
 
class GuestForm(forms.Form):
    guest_name = forms.CharField(
        label = "Your name",
        widget = forms.TextInput(
            attrs = {
                'class':'form-control',
                'max_length : 100'
                'id' : 'fname',
                'placeholder' : 'Your name',
            }
        )
    )

story6/views.py
from . import forms
from .models import Activity, Guest
from django.shortcuts import render, redirect
from .forms import ActivityForm, GuestForm

# Create your views here.

def addActivity(request):
    activity_form = forms.ActivityForm()
    if request.method == 'POST':
        activity_form_input = forms.ActivityForm(request.POST)
        if activity_form_input.is_valid():
            data = activity_form_input.cleaned_data
            activity_input = Activity()
            activity_input.activity_name = data['activity_name']
            activity_input.save()
            # current_data = Activity.objects.all()

            return redirect('/listActivity')  
        else:
            # current_data = Activity.objects.all()
            return render(request, 'add2.html',{'form':activity_form, 'status':'failed'})
    else:
        # current_data = Activity.objects.all()
        return render(request, 'add2.html',{'form':activity_form})


def listActivity(request):
    activity = Activity.objects.all()
    guest = Guest.objects.all()
    return render(request, 'list2.html',{'activity': activity, 'guest':guest})

def deleteUser(request, delete_id):
    # if request.method == "POST":
    activity = Activity.objects.all()
    guest = Guest.objects.all()
    print(delete_id)
    guest_to_delete = Guest.objects.get(id=delete_id)
    guest_to_delete.delete()
    # return render(request, 'story6/listActivity.html', {'kegiatan': kegiatan, 'orang': orang})
    return redirect('/listActivity')

def deleteActivity(request, delete_id):
    try:
        deleted_activity = Activity.objects.get(pk = delete_id)
        deleted_activity.delete()
        return redirect('/listActivity')
    except:
        return redirect('/listActivity')

def join(request, task_id):
    guest_form = forms.GuestForm()
    if request.method == 'POST':
        guest_form_input = forms.GuestForm(request.POST)
        if guest_form_input.is_valid():
            data = guest_form_input.cleaned_data
            newGuest = Guest()
            newGuest.guest_name = data['guest_name']
            newGuest.activity = Activity.objects.get(id = task_id)
            newGuest.save()
            return redirect('/listActivity')  
        else:
            return render(request, 'join.html',{'form':guest_form, 'status':'failed'})
    else:
        return render(request, 'join.html',{'form':guest_form})

story6/templates/add2.html
<!DOCTYPE HTML>
 
{% extends "base.html" %}
 
<html>
    {% block content %} 
 
    <div id="fh5co-started" class="fh5co-bg-dark">
        <div class="overlay"></div>
        <div class="container">
            <div class="row animate-box">
                <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                    <h2 id="h2-section">Add activity!</h2>
                    <br></br>
                    <br></br>
                </div>
                <div id="fh5co-consult" class="fh5co-bg-dark-2">
                <div class="video fh5co-video" style="background-image: url(/static/activity.jpg);">
                    <div class="overlay"></div>
                </div>
                    
                <div class="choose animate-box">
                    <h2>What are you going to do?</h2>
                    <form action="#" method="post">
                    {% csrf_token %}
                        <div class="row form-group">
                            <div class="col-md-12">
                                {{ form.activity_name }}
                            </div>
                        </div>
 
                        <div class="form-group">
                            <input type="submit" value="Add Activity" class="btn btn-primary">
                        </div>
                    </form> 
                </div>
            </div>
        </div>
    </div>
 
 
    {% endblock %}
</html>

story6/templates/join.html
<!DOCTYPE HTML>
 
{% extends "base.html" %}
 
<html>
    {% block content %} 
 
    <div id="fh5co-started" class="fh5co-bg-dark">
        <div class="overlay"></div>
        <div class="container">
            <div class="row animate-box">
                <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                    <h2 id="h2-section">Wow, you wanna join?</h2>
                    <br></br>
                    <br></br>
                </div>
                <div id="fh5co-consult" class="fh5co-bg-dark-2">
                <div class="video fh5co-video" style="background-image: url(/static/activity2.jpg);">
                    <div class="overlay"></div>
                </div>
 
                <div class="choose animate-box">
                    <h2>Add your name here!</h2>
                    <form action="#" method="post">
                    {% csrf_token %}
                        <div class="row form-group">
                            <div class="col-md-12">
                                {{ form.guest_name }}
                            </div>
                        </div>
 
                        <div class="form-group">
                            <input type="submit" value="Join Activity" class="btn btn-primary">
                        </div>
                    </form> 
                </div>
 
            </div>
        </div>
    </div>
 
 
    {% endblock %}
</html>

story6/templates/list2.html
<!DOCTYPE HTML>
 
{% extends "base.html" %}
 
<html>
    {% block content %} 
 
 
    {% if listActivity.count == 0 %}
    <div id="fh5co-work" class="fh5co-bg-dark">
        <div id="fh5co-blog">
            <div class="container">
                <div class="row animate-box">
                    <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                        <h2 id="h2-section2">No activity added</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    {% else %}
    <div id="fh5co-work" class="fh5co-bg-dark">
        <div id="fh5co-blog">
            <div class="container">
                <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                    <h2 id="h2-section2">Activity List</h2>
                </div>
                <div class="row">
                    {% for act in activity %}
                    <div class="col-md-4">
                        <div class="fh5co-blog animate-box">
                            <div class="blog-text">
                                <a href = "{% url 'story6:deleteActivity' delete_id=act.pk %}">
                                <div class="timeline-badge"><i class="fa fa-trash-o"></i></div>
                                </a>
                                <h1 id="h2-section2"><a> {{act.activity_name}} </a></h1>
                                <a> Participants: </a>
                                {% for a in guest %}
                                {% if a.activity == act %}
                                <div>
                                    <h3 id="h3-up"><a> > {{a.guest_name}}</a>
                                    <a style="text-decoration: underline;" href = "{% url 'story6:delete' delete_id=a.pk %}">
                                        (remove)
                                    </a>
                                    <h3>
                                </div>
                                {% endif %}
                                {% endfor %}
                                <a href = "{% url 'story6:join' task_id=act.pk  %}">
                                    <input type="submit" value="Join Activity" class="btn btn-success">
                                </a>
                            </div> 
                        </div>
                    </div>
                    {% endfor %}
                    <br></br>
                    <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                        <a href = "{% url 'story6:addActivity' %}">
                        <input type="submit" value="ADD MORE ACTIVITY" class="btn btn-success">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
 
    {% endif %}
 
    {% endblock %}
</html>