Story1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('HOMEPAGE.urls')),
    path('', include('myspace.urls')),
    path('', include('story6.urls')),
]

myspace/urls.py
from django.urls import path
from . import views

app_name = 'myspace'

urlpatterns = [
    path('myspace/', views.myspace, name='space'),
    path('addSubject/', views.addSubject, name='addSubject'),
    path('listSubject/', views.listSubject, name='listSubject'),
    path('delete/P<int:delete_id>/', views.delete, name='delete'),
    # path('url-yang-diinginkan/', views.nama_fungsi, name='nama_fungsi')
    # path('profile/', views.profile, name='profile'),
    # dilanjutkan ...
]

myspace/models.py
from django.db import models

# Create your models here.
class Subject(models.Model):
    subject_name = models.CharField(max_length = 100)
    credits_amount = models.IntegerField()
    room = models.CharField(max_length = 100)
    lecturer = models.CharField(max_length = 100)
    year = models.CharField(max_length = 100)
    description = models.CharField(max_length = 1000, null = True)

    def __str__(self):
        return self.subject_name

myspace/forms.py
from django import forms 

class SubjectForm(forms.Form):
    subject_name = forms.CharField(
        label = "Subject name",
        widget = forms.TextInput(
            attrs = {
                'class':'form-control',
                'max_length : 100'
                'id' : 'fname',
                'placeholder' : 'Subject name',
            }
        )
    )

    credits_amount = forms.IntegerField(
        label = "Amount of credits",
        widget = forms.NumberInput(
            attrs={
                'class':'form-control',
                'min':'1',
                'max':'6',
                'id' : 'fname',
                'placeholder' : 'Amount of credits',
            }
        )
    )

    room = forms.CharField(
        label = "Room", 
        widget = forms.TextInput(
            attrs={
                'class':'form-control',
                'max_length : 100'
                'id' : 'fname',
                'placeholder' : 'Room',
            }
        )
    )

    lecturer = forms.CharField(
        label = "Lecturer name", 
        widget = forms.TextInput(
            attrs={
                'class':'form-control',
                'max_length : 100'
                'id' : 'fname',
                'placeholder' : 'Lecturer name',
            }
        )
    )

    description = forms.CharField(
        label = "Subject description", 
        widget = forms.Textarea(
            attrs={
                'class':'form-control',
                'max_length : 100'
                'cols' : '30',
                'rows' : '10',
                'id' : 'fname',
                'placeholder' : 'Subject description',
            }
        )
    )
    
    year = forms.CharField(
        label = "Semester", 
        widget = forms.TextInput(
            attrs={
                'class':'form-control',
                'max_length : 100'
                'id' : 'fname',
                'placeholder' : 'Semester',
            }
        )
    )

myspace/views.py
from . import forms
from .models import Subject
from django.shortcuts import render, redirect

# Create your views here.
def myspace(request):
    return render(request, 'space.html')

def addSubject(request):
    subject_form = forms.SubjectForm()
    if request.method == 'POST':
        subject_form_input = forms.SubjectForm(request.POST)
        if subject_form_input.is_valid():
            data = subject_form_input.cleaned_data
            subject_input = Subject()
            subject_input.subject_name = data['subject_name']
            subject_input.credits_amount = data['credits_amount']
            subject_input.room = data['room']
            subject_input.lecturer = data['lecturer']
            subject_input.year = data['year']
            subject_input.description = data['description']
            subject_input.save()
            current_data = Subject.objects.all()

            return redirect('/listSubject')  
        else:
            current_data = Subject.objects.all()
            return render(request, 'add.html',{'form':subject_form, 'status':'failed','data':current_data})
    else:
        current_data = Subject.objects.all()
        return render(request, 'add.html',{'form':subject_form,'data':current_data})


def listSubject(request):
    data = Subject.objects.all()
    return render(request, 'list.html',{'listSubject' : data})

def delete(request, delete_id):
    try:
        deleted_subject = Subject.objects.get(pk = delete_id)
        deleted_subject.delete()
        return redirect('/listSubject')
    except:
        return redirect('/listSubject')

myspace/templates/add.html
<!DOCTYPE HTML>

{% extends "base.html" %}

<html>
	{% block content %}	

	<div id="fh5co-started" class="fh5co-bg-dark">
		<div class="overlay"></div>
		<div class="container">
			<div class="row animate-box">
				<div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
					<h2 id="h2-section">Add your subject here!</h2>
					<br></br>
					<br></br>
				</div>
				<div id="fh5co-consult" class="fh5co-bg-dark-2">
				<div class="video fh5co-video" style="background-image: url(/static/schedule.jpg);">
					<div class="overlay"></div>
				</div>
					
				<div class="choose animate-box">
					<h2>Subject Form</h2>
					<form action="#" method="post">
					{% csrf_token %}
						<div class="row form-group">
							<div class="col-md-12">
								{{ form.subject_name }}
							</div>
						</div>
						<div class="row form-group">
							<div class="col-md-12">
								{{ form.credits_amount }}
							</div>
						</div>

						<div class="row form-group">
							<div class="col-md-12">
								{{ form.room }}
							</div>
						</div>

						<div class="row form-group">
							<div class="col-md-12">
								{{ form.lecturer }}
							</div>
						</div>

						<div class="row form-group">
							<div class="col-md-12">
								{{ form.year }}
							</div>
						</div>

						<div class="row form-group">
							<div class="col-md-12">
								{{ form.description }}
							</div>
						</div>
						
						<div class="form-group">
							<input type="submit" value="Add Subject" class="btn btn-primary">
						</div>
					</form>	
				</div>
			</div>
		</div>
	</div>


	{% endblock %}
</html>

myspace/templates/list.html
<!DOCTYPE HTML>

{% extends "base.html" %}

<html>
	{% block content %}	


    {% if listSubject.count == 0%}
    <div id="fh5co-work" class="fh5co-bg-dark">
		<div id="fh5co-blog">
		    <div class="container">
                <div class="row animate-box">
                    <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                        <h2 id="h2-section2">No subject added</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    {% else %}
	<div id="fh5co-work" class="fh5co-bg-dark">
		<div id="fh5co-blog">
		    <div class="container">
                <div class="row animate-box">
                    <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                        <h2 id="h2-section2">Subject list</h2>
                    </div>
                    <table class="table">
                    <tr>
                        <th>Subject</th>
                        <th>Description</th>
                        <th>Credits</th>
                        <th>Lecturer</th>
                        <th>Room</th>
                        <th>Year</th>
                        <th>Remove</th>
                    </tr>

                    {% for subject in listSubject %}
                    <tr>
                        <td> {{subject.subject_name}} </td>
                        <td> {{subject.description}} </td>
                        <td> {{subject.credits_amount}} </td>
                        <td> {{subject.lecturer}} </td>
                        <td> {{subject.room}} </td>
                        <td> {{subject.year}} </td>
                        <td>
                            <a href = "{% url 'myspace:delete' delete_id=subject.pk %}">
                            <button class="btn btn-icon btn-danger"></button>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                    </table>
                    <br></br>
                    <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                        <a href = "{% url 'myspace:addSubject' %}">
                        <input type="submit" value="ADD MORE SUBJECT" class="btn btn-success">
                        </a>
                    </div>
                </div>
			</div>
		</div>
	</div>

    {% endif %}

	{% endblock %}
</html>

myspace/templates/space.html
<!DOCTYPE HTML>

{% extends "base.html" %}

<html>
	{% block content %}	

	<div id="fh5co-features" class="animate-box">
		<div class="container">
			<div class="services-padding">
				<div class="row">
					<div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
						<h1 id="h2-section">My Space</h1>
					</div>
					<div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
						<h3 id="space-font">Main Interests</h3>
					</div>
				</div>
				<div class="row">
					<div class="col-md-4 text-center">
						<div class="feature-left">
							<span class="icon">
								<i class="fa fa-music"></i>
							</span>
							<div class="feature-copy">
								<h3>Music</h3>
								<p>I love music like i love my self. My favorite music genres are Jazz and Pop!</p>
							</div>
						</div>
					</div>
					<div class="col-md-4 text-center">
						<div class="feature-left">
							<span class="icon">
								<i class="fa fa-microphone"></i>
							</span>
							<div class="feature-copy">
								<h3>Singing</h3>
								<p>I really love to sing since i was a kid. It is one of my hobbies!</p>
							</div>
						</div>
					</div>
					<div class="col-md-4 text-center">
						<div class="feature-left">
							<span class="icon">
								<i class="fa fa-heart"></i>
							</span>
							<div class="feature-copy">
								<h3>Volunteer Work</h3>
								<p>I like to join a volunteer work like committees</p>
							</div>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-md-4 text-center">
						<div class="feature-left">
							<span class="icon">
								<i class="fa fa-commenting-o"></i>
							</span>
							<div class="feature-copy">
								<h3>Networking Events</h3>
								<p>Socialize with people through networking events, why not?</p>
							</div>
						</div>
					</div>
					<div class="col-md-4 text-center">
						<div class="feature-left">
							<span class="icon">
								<i class="fa fa-desktop"></i>
							</span>
							<div class="feature-copy">
								<h3>UI / UX</h3>
								<p>I became slowly interested for UI/UX things</p>
							</div>
						</div>
					</div>
					<div class="col-md-4 text-center">
						<div class="feature-left">
							<span class="icon">
								<i class="fa fa-laptop"></i>
							</span>
							<div class="feature-copy">
								<h3>Computing</h3>
								<p>Since i am a CS student, i have to love this!</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div id="fh5co-work" class="fh5co-bg-dark">
		<div class="container">
			<div class="row animate-box">
				<div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
					<h3 id="space-font">Project</h3>
				</div>
			</div>
			<div class="row">
				<div class="col-md-3 text-center col-padding animate-box">
					<a href="https://nobarkorid.herokuapp.com/" class="work" style="background-image: url(/static/nobarkor.png);">
						<div class="desc">
							<h3>Nobarkor.id</h3>
							<span>Website</span>
						</div>
					</a>
				</div>
				<div class="col-md-3 text-center col-padding animate-box">
					<a href="https://nobarkorid.herokuapp.com/" class="work" style="background-image: url(/static/nobarkor2.png);">
						<div class="desc">
							<h3>Nobarkor.id</h3>
							<span>Website</span>
						</div>
					</a>
				</div>
				<div class="col-md-3 text-center col-padding animate-box">
					<a href="https://nobarkorid.herokuapp.com/" class="work" style="background-image: url(/static/nobarkor3.png);">
						<div class="desc">
							<h3>Nobarkor.id</h3>
							<span>Website</span>
						</div>
					</a>
				</div>
				<div class="col-md-3 text-center col-padding animate-box">
					<a href="https://nobarkorid.herokuapp.com/" class="work" style="background-image: url(/static/nobarkor4.png);">
						<div class="desc">
							<h3>Nobarkor.id</h3>
							<span>Website</span>
						</div>
					</a>
				</div>
			</div>
		</div>
	</div>

	<div id="fh5co-work" class="fh5co-bg-dark">
		<div class="container">
			<div class="row animate-box">
				<div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
					<h3 id="space-font">My Favorite Series</h3>
				</div>
			</div>
			<div class="row">
				<div class="col-md-3 text-center col-padding animate-box">
					<a href="https://en.wikipedia.org/wiki/Guardian:_The_Lonely_and_Great_God" class="work" style="background-image: url(/static/goblin.jpg);">
						<div class="desc">
							<h3>Goblin</h3>
							<span>K-drama</span>
						</div>
					</a>
				</div>
				<div class="col-md-3 text-center col-padding animate-box">
					<a href="https://en.wikipedia.org/wiki/Stranger_Things" class="work" style="background-image: url(/static/stranger.jpg);">
						<div class="desc">
							<h3>Stranger Things</h3>
							<span>Netflix</span>
						</div>
					</a>
				</div>
				<div class="col-md-3 text-center col-padding animate-box">
					<a href="https://en.wikipedia.org/wiki/The_Gifted_(Thai_TV_series)" class="work" style="background-image: url(/static/thegifted.jpg);">
						<div class="desc">
							<h3>The Gifted</h3>
							<span>Thai Series</span>
						</div>
					</a>
				</div>
				<div class="col-md-3 text-center col-padding animate-box">
					<a href="https://en.wikipedia.org/wiki/Ao_Haru_Ride" class="work" style="background-image: url(/static/aoharu.jpg);">
						<div class="desc">
							<h3>Ao Haru Ride</h3>
							<span>Anime</span>
						</div>
					</a>
				</div>
			</div>
		</div>
	</div>

	<div id="fh5co-work" class="fh5co-bg-dark">
		<div class="container">
			<div class="row animate-box">
				<div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
					<h3 id="space-font">My Idols</h3>
				</div>
			</div>
			<div class="row">
				<div class="col-md-3 text-center col-padding animate-box">
					<a href="https://www.youtube.com/user/GMMTVSPOTLIKE" class="work" style="background-image: url(/static/gmmtv.jpg);">
						<div class="desc">
							<h3>GMMTV Boys</h3>
							<span>Thai Actors</span>
						</div>
					</a>
				</div>
				<div class="col-md-3 text-center col-padding animate-box">
					<a href="https://www.youtube.com/channel/UC9rMiEjNaCSsebs31MRDCRA" class="work" style="background-image: url(/static/skz.jpg);">
						<div class="desc">
							<h3>Stray Kids</h3>
							<span>K-pop Boyband</span>
						</div>
					</a>
				</div>
				<div class="col-md-3 text-center col-padding animate-box">
					<a href="https://en.wikipedia.org/wiki/TharnType:_The_Series" class="work" style="background-image: url(/static/mewgulf.jpg);">
						<div class="desc">
							<h3>MewGulf</h3>
							<span>Thai Actors</span>
						</div>
					</a>
				</div>
				<div class="col-md-3 text-center col-padding animate-box">
					<a href="https://en.wikipedia.org/wiki/Cha_Eun-woo" class="work" style="background-image: url(/static/cha.jpg);">
						<div class="desc">
							<h3>Cha Eun-woo</h3>
							<span>Korean Actor</span>
						</div>
					</a>
				</div>
			</div>
		</div>
	</div>

	<div id="fh5co-work" class="fh5co-bg-dark">
		<div class="container">
			<div class="row animate-box">
				<div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
					<h3 id="space-font">My Favorite Songs</h3>
				</div>
			</div>
			<div class="row">
				<div class="col-md-3 text-center col-padding animate-box">
					<iframe src="https://open.spotify.com/embed/track/71WZ7yFuwxmQz5jJUpvkGv" width="250" height="300" frameborder="100" allowtransparency="true" allow="encrypted-media"></iframe>
				</div>
				<div class="col-md-3 text-center col-padding animate-box">
					<iframe src="https://open.spotify.com/embed/track/7rgjkzZBhBjObaYsvq8Ej0" width="250" height="300" frameborder="100" allowtransparency="true" allow="encrypted-media"></iframe>
				</div>
				<div class="col-md-3 text-center col-padding animate-box">
					 <iframe src="https://open.spotify.com/embed/track/6z1kLsntE7FuzKZHZWrXYN" width="250" height="300" frameborder="100" allowtransparency="true" allow="encrypted-media"></iframe>
				</div>
				<div class="col-md-3 text-center col-padding animate-box">
					<a href="#" class="work">
						<iframe src="https://open.spotify.com/embed/track/7I0vl97TYZW86qYdgcD1qu" width="250" height="300" frameborder="100" allowtransparency="true" allow="encrypted-media"></iframe>
					</a>
				</div>
			</div>
		</div>
	</div>


	{% endblock %}
</html>